
"""ANN.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1h8sBOOMk8oY9Bmgff-q7Nwrl1-9Z-0bt
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import itertools

# Keras / TensorFlow
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Dropout, Flatten, BatchNormalization
from tensorflow.keras.callbacks import EarlyStopping
from tensorflow.keras.optimizers import Adam
from tensorflow.keras.utils import to_categorical

# Sklearn
from sklearn.preprocessing import LabelEncoder, MinMaxScaler
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report, confusion_matrix

# Mount Google Drive
from google.colab import drive
drive.mount('/content/drive')

# Load dataset
file_path = '/content/drive/MyDrive/datasetV3.csv'
data = pd.read_csv(file_path, sep=';', header=None)

# Remove first row
data = data.drop(data.index[0])

# Encode labels
label_encoder = LabelEncoder()
data.iloc[:, 25] = label_encoder.fit_transform(data.iloc[:, 25])

# Convert non-numeric values
data = data.apply(pd.to_numeric, errors='coerce')

# Remove NaN
data = data.dropna()

# Features and labels
X = data.iloc[:, :-1].values
y = to_categorical(data.iloc[:, 25])

# Normalization
scaler = MinMaxScaler()
X = scaler.fit_transform(X)

# Split dataset
X_train, X_temp, y_train, y_temp = train_test_split(
    X, y, train_size=80, random_state=42
)

X_test, X_val, y_test, y_val = train_test_split(
    X_temp, y_temp, test_size=0.5, random_state=42
)

print("Train:", len(X_train), "Val:", len(X_val), "Test:", len(X_test))

# Build ANN model
def build_model():
    model = Sequential()
    model.add(Dense(64, activation='relu', input_shape=(X.shape[1],)))
    model.add(BatchNormalization())
    model.add(Dropout(0.3))

    model.add(Dense(32, activation='relu'))
    model.add(BatchNormalization())
    model.add(Dropout(0.3))

    model.add(Dense(16, activation='relu'))
    model.add(Dense(4, activation='softmax'))

    model.compile(
        optimizer=Adam(learning_rate=0.001),
        loss='categorical_crossentropy',
        metrics=['accuracy']
    )
    return model

model = build_model()
model.summary()

# Training
early_stopping = EarlyStopping(monitor='val_loss', patience=10, restore_best_weights=True)

history = model.fit(
    X_train, y_train,
    epochs=100,
    batch_size=16,
    validation_data=(X_val, y_val),
    callbacks=[early_stopping]
)

# Evaluation
model.evaluate(X_test, y_test)

# Plot accuracy & loss
pd.DataFrame(history.history)[['accuracy', 'val_accuracy']].plot().grid(True)
pd.DataFrame(history.history)[['loss', 'val_loss']].plot().grid(True)

# Prediction
y_pred = np.argmax(model.predict(X_test), axis=1)
y_true = np.argmax(y_test, axis=1)

# Metrics
print(classification_report(y_true, y_pred))

# Confusion matrix
cm = confusion_matrix(y_true, y_pred)

plt.imshow(cm, cmap=plt.cm.Blues)
plt.title("Confusion Matrix")
plt.colorbar()
plt.xlabel("Predicted")
plt.ylabel("True")
plt.show()
